robot_base_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

robot_base_velocity_controller:
  # type: "diff_drive_controller/DiffDriveController"
  # left_wheel: 'joint_right_wheel'
  # right_wheel: 'joint_left_wheel'
  # publish_rate: 50
  # pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  # twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  # cmd_vel_timeout: 0.25
  # wheel_separation : 0.5
  # wheel_radius : 0.08
  # base_frame_id: base_link
  # odom_frame_id: odom
  # enable_odom_tf: false
  # estimate_velocity_from_position: false
  # wheel_separation_multiplier: 1.0 
  # wheel_radius_multiplier    : 1.0 
  # linear:
  #   x:
  #     has_velocity_limits    : true
  #     max_velocity           : 2.0   
  #     has_acceleration_limits: true
  #     max_acceleration       : 3.0   
  # angular:
  #   z:
  #     has_velocity_limits    : true
  #     max_velocity           : 3.0   
  #     has_acceleration_limits: true
  #     max_acceleration       : 6.0
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - joint_left_wheel
    - joint_right_wheel
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    hip: {trajectory: 0.1, goal: 0.1}
    shoulder: {trajectory: 0.1, goal: 0.1}
    elbow: {trajectory: 0.1, goal: 0.1}
    wrist: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

/gazebo_ros_control:
    pid_gains:
      # joint_left_wheel: {p: 20.0, i: 5.0, d: 0.0, i_clamp: 1.0}
      # joint_right_wheel: {p: 20.0, i: 5.0, d: 0.0, i_clamp: 1.0}
      joint_left_wheel : {p: 20.0, i: 5.0, d: 0.0, i_clamp: 1.0}
      joint_right_wheel: {p: 20.0, i: 5.0, d: 0.0, i_clamp: 1.0}
